# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: "Deploy"
on:
  push:
    branches:
      - "main"
  workflow_dispatch:
permissions:
  contents: "read"
  pages: "write"
  id-token: "write"
concurrency:
  group: "pages"
  cancel-in-progress: false
jobs:
  main:
    name: "Main"
    runs-on: "ubuntu-latest"
    environment:
      name: "github-pages"
      url: "${{steps.deployment.outputs.page_url}}"
    steps:
      - name: "Checkout Repository"
        uses: "actions/checkout@v4.1.1"
      - name: "Setup Deno"
        uses: "denoland/setup-deno@v1.1.3"
        with:
          deno-version: "^1.39.0"
      - name: "Build GitHub Pages"
        run: |
          deno run "--allow-read=$($Env:GITHUB_WORKSPACE)" "--allow-write=$($Env:GITHUB_WORKSPACE)" builder.ts
        shell: "pwsh"
      - name: "Configure GitHub Pages"
        uses: "actions/configure-pages@v4.0.0"
      - name: "Upload GitHub Pages Artifact"
        uses: "actions/upload-pages-artifact@v3.0.0"
        with:
          path: "_site/"
      - name: "Deploy To GitHub Pages"
        id: "deployment"
        uses: "actions/deploy-pages@v4.0.0"
